### ISSUE TITLE
Update meta tags and favicon

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#49]
The metatags and favicon on the app are still the default from the create react app template.
We should update the:
- [x] tabula favicon
- [x] metatags on the home page
  - [x] `og:title` "Tabula"
  - [x] `og:site_name` "Tabula"
  - [x] `og:description` "Instant web3 publications for writers, DAOs, and any Ethereum-based account."
  - [x] `og:type` website
  - [x] `og:url` https://tabula.gg
  - [x] `og:image` full URL to a preview image
- [x] metatags on a publication page
  - [x] `og:title` "{Publication Name}"
  - [x] `og:site_name` "Tabula"
  - [x] `og:description` "{Publication Description}"
  - [x] `og:type` website
  - [x] `og:url` https://tabula.gg/{publication Id}
  - [ ] `og:image` full URL to publication preview image
- [x] metatags on an article page
  - [x] `og:title` "{Article Title}"
  - [x] `og:site_name` "{Publication Name}"
  - [x] `og:description` "{Article Description}"
  - [x] `og:type` website
  - [x] `og:url` https://tabula.gg/{publication Id}-{article id}
  - [x] `og:image` full URL to article preview image

**Comment by asgeir-eth** [comment]
@cedricwaxwing Do we have a favicon for Tabula?

**Comment by manboy-eth** [comment]
Yes, I will take a look

**Comment by auryn-macmillan** [comment]
Thanks for looking into this, @manboy-eth.

Quick fix is probably just to hardcode the metatags to the values defined in the "metatags on the home page" section above.

Then we can create a separate issue for this and add it to a future milestone.
